version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - syncier-network

  keycloak:
    image: jboss/keycloak:4.0.0.Final
    container_name: keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - syncier-network

volumes:
  postgres-data:
  keycloak-data:

networks:
  syncier-network:
    driver: bridge
