version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - syncier-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: keycloak
    environment:
      KC_DB_URL: 'jdbc:postgresql://postgres:5432/keycloak?useSSL=false'
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}    
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    command: ["start-dev", "--http-relative-path", "/auth"]
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - syncier-network

volumes:
  postgres-data:
  keycloak-data:

networks:
  syncier-network:
    driver: bridge
